name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: free60/libxenon:latest

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Export variables
      run: |
        echo DEVKITXENON=/usr/local/xenon >> $GITHUB_ENV
        echo /usr/local/xenon/bin >> $GITHUB_PATH
        echo /usr/local/xenon/usr/bin >> $GITHUB_PATH
    - name: Build
      run: make
    - uses: actions/upload-artifact@v4
      with:
        name: examples
        path: bin/**/*.elf32
